/**
 * Reports Page
 * 
 * Reads: Snapshot report, Delta report, Evidence bundle metadata, Hashes
 * Props: { reports: ReportIndex }
 * 
 * RULES:
 * - Every report has a hash
 * - Evidence bundles are traceable
 * - Reports generated by backend, NOT UI
 * - Download is direct file fetch
 * - All report actions appear in activity timeline and system proof
 * - Gate actions by authorities
 */

import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { toast } from "sonner";
import { 
  FileText, 
  Hash, 
  Download, 
  Calendar, 
  Package, 
  Plus,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Clock
} from "lucide-react";
import { useLocation } from "wouter";
import type { ReportIndex, ReportSummary, EvidenceBundleMetadata } from "@/contracts/activity";
import { SEED_DATA } from "@/demo/seed";
import { useAuthorities, AuthorityGate } from "@/hooks/useAuthorities";

interface ReportsPageProps {
  reports?: ReportIndex;
}

// Use centralized seed data - in production, this comes from TuringCore API
const DEMO_REPORTS = SEED_DATA.reports;
const DEMO_EVIDENCE_BUNDLES = SEED_DATA.evidenceBundles;

function formatDate(isoString: string): string {
  return new Date(isoString).toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

function formatDateTime(isoString: string): string {
  return new Date(isoString).toLocaleString('en-AU', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getReportTypeBadgeVariant(type: string): 'default' | 'secondary' | 'outline' {
  switch (type) {
    case 'SNAPSHOT': return 'default';
    case 'DELTA': return 'secondary';
    case 'ANNUAL_STATEMENT': return 'default';
    case 'TAX_SUMMARY': return 'outline';
    case 'AUDIT_TRAIL': return 'secondary';
    default: return 'outline';
  }
}

export default function Reports({ reports }: ReportsPageProps) {
  const { isAuthenticated, loading } = useAuth();
  const [, setLocation] = useLocation();
  const { has, executionMode, isSyntheticIdentity } = useAuthorities();
  const [downloadingReport, setDownloadingReport] = useState<string | null>(null);
  const [downloadingBundle, setDownloadingBundle] = useState<string | null>(null);

  // Wait for auth to load before checking
  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-slate-500">Loading reports...</div>
      </div>
    );
  }

  if (!isAuthenticated) {
    setLocation('/login');
    return null;
  }

  const reportList = reports?.reports || DEMO_REPORTS;
  const evidenceBundles = DEMO_EVIDENCE_BUNDLES;

  // Handle report generation request
  const handleGenerateReport = () => {
    if (!has('REPORT_GENERATE')) {
      toast.error('Insufficient authority', {
        description: 'Required: REPORT_GENERATE',
      });
      return;
    }

    // In production, this would call the TuringCore API
    toast.info('Report generation requested', {
      description: `Mode: ${executionMode} | Reports are generated by the backend`,
    });
  };

  // Handle report download
  const handleDownloadReport = async (report: ReportSummary) => {
    if (!has('REPORT_DOWNLOAD')) {
      toast.error('Insufficient authority', {
        description: 'Required: REPORT_DOWNLOAD',
      });
      return;
    }

    setDownloadingReport(report.reportId);

    try {
      // Log download action (recorded in activity timeline)
      console.log('[Report Download]', {
        reportId: report.reportId,
        hash: report.hash,
        timestamp: new Date().toISOString(),
        executionMode,
        hasUrl: !!report.downloadUrl,
      });

      // In LIVE mode with real URL: direct file fetch
      // In DEMO mode: simulated download
      if (report.downloadUrl) {
        // Real artefact URL from TuringCore API
        window.open(report.downloadUrl, '_blank');
        toast.success('Report download started', {
          description: (
            <div className="text-xs font-mono">
              <div>Report: {report.reportId}</div>
              <div>Hash: {report.hash}</div>
              <div>Mode: LIVE</div>
            </div>
          ),
        });
      } else {
        // DEMO mode: simulate download
        await new Promise(resolve => setTimeout(resolve, 500));
        toast.info('Report download simulated', {
          description: (
            <div className="text-xs font-mono">
              <div>Report: {report.reportId}</div>
              <div>Hash: {report.hash}</div>
              <div>Mode: DEMO (no real artefact)</div>
            </div>
          ),
        });
      }
    } finally {
      setDownloadingReport(null);
    }
  };

  // Handle evidence bundle download
  const handleDownloadBundle = async (bundle: EvidenceBundleMetadata) => {
    if (!has('REPORT_DOWNLOAD')) {
      toast.error('Insufficient authority', {
        description: 'Required: REPORT_DOWNLOAD',
      });
      return;
    }

    setDownloadingBundle(bundle.bundleId);

    try {
      // Log download action
      console.log('[Evidence Bundle Download]', {
        bundleId: bundle.bundleId,
        hash: bundle.hash,
        timestamp: new Date().toISOString(),
        executionMode,
        hasUrl: !!bundle.downloadUrl,
      });

      // In LIVE mode with real URL: direct file fetch
      // In DEMO mode: simulated download
      if (bundle.downloadUrl) {
        // Real artefact URL from TuringCore API
        window.open(bundle.downloadUrl, '_blank');
        toast.success('Evidence bundle download started', {
          description: (
            <div className="text-xs font-mono">
              <div>Bundle: {bundle.bundleId}</div>
              <div>Hash: {bundle.hash}</div>
              <div>Documents: {bundle.documentCount}</div>
              <div>Mode: LIVE</div>
            </div>
          ),
        });
      } else {
        // DEMO mode: simulate download
        await new Promise(resolve => setTimeout(resolve, 500));
        toast.info('Evidence bundle download simulated', {
          description: (
            <div className="text-xs font-mono">
              <div>Bundle: {bundle.bundleId}</div>
              <div>Hash: {bundle.hash}</div>
              <div>Documents: {bundle.documentCount}</div>
              <div>Mode: DEMO (no real artefact)</div>
            </div>
          ),
        });
      }
    } finally {
      setDownloadingBundle(null);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 py-8">
      <div className="container max-w-6xl">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <FileText className="w-8 h-8 text-slate-700" />
                <h1 className="text-3xl font-bold text-slate-900">Reports</h1>
              </div>
              <p className="text-slate-600">
                Snapshot and delta reports with evidence bundle metadata and hashes
              </p>
            </div>
            <AuthorityGate authority="REPORT_GENERATE">
              <Button onClick={handleGenerateReport}>
                <Plus className="w-4 h-4 mr-2" />
                Request Report
              </Button>
            </AuthorityGate>
          </div>
        </div>

        {/* Execution Context Info */}
        {executionMode === 'DEMO' && (
          <Alert className="mb-4 border-amber-200 bg-amber-50">
            <AlertTriangle className="h-4 w-4 text-amber-600" />
            <AlertTitle className="text-amber-800">Demo Mode</AlertTitle>
            <AlertDescription className="text-amber-700">
              {isSyntheticIdentity && 'Using synthetic identity. '}
              Downloads will be simulated. Reports are generated by the backend, not the UI.
            </AlertDescription>
          </Alert>
        )}

        {/* Authority Status */}
        <div className="mb-6 flex flex-wrap gap-4 text-sm">
          <div className="flex items-center gap-1">
            {has('REPORT_READ') ? (
              <><CheckCircle2 className="w-4 h-4 text-green-600" /><span className="text-green-700">REPORT_READ</span></>
            ) : (
              <><XCircle className="w-4 h-4 text-slate-400" /><span className="text-slate-500">REPORT_READ</span></>
            )}
          </div>
          <div className="flex items-center gap-1">
            {has('REPORT_GENERATE') ? (
              <><CheckCircle2 className="w-4 h-4 text-green-600" /><span className="text-green-700">REPORT_GENERATE</span></>
            ) : (
              <><XCircle className="w-4 h-4 text-slate-400" /><span className="text-slate-500">REPORT_GENERATE</span></>
            )}
          </div>
          <div className="flex items-center gap-1">
            {has('REPORT_DOWNLOAD') ? (
              <><CheckCircle2 className="w-4 h-4 text-green-600" /><span className="text-green-700">REPORT_DOWNLOAD</span></>
            ) : (
              <><XCircle className="w-4 h-4 text-slate-400" /><span className="text-slate-500">REPORT_DOWNLOAD</span></>
            )}
          </div>
        </div>

        {/* Summary */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Total Reports</CardDescription>
              <CardTitle className="text-2xl">{reportList.length}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Evidence Bundles</CardDescription>
              <CardTitle className="text-2xl">{evidenceBundles.length}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Latest Report</CardDescription>
              <CardTitle className="text-lg">{formatDate(reportList[0]?.generatedAt || '')}</CardTitle>
            </CardHeader>
          </Card>
        </div>

        {/* Reports Table */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Report Index</CardTitle>
            <CardDescription>
              All generated reports with evidence bundle references. Downloads are direct file fetches.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead>Hash</TableHead>
                  <TableHead>Evidence</TableHead>
                  <TableHead></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reportList.map((report) => (
                  <TableRow key={report.reportId}>
                    <TableCell>
                      <div className="font-medium">{report.title}</div>
                      <div className="text-xs text-slate-500 font-mono">{report.reportId}</div>
                    </TableCell>
                    <TableCell>
                      <Badge variant={getReportTypeBadgeVariant(report.reportType)}>
                        {report.reportType.replace(/_/g, ' ')}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm">
                      <div className="flex items-center gap-1">
                        <Calendar className="w-3 h-3 text-slate-400" />
                        {formatDate(report.periodStart)} - {formatDate(report.periodEnd)}
                      </div>
                    </TableCell>
                    <TableCell className="text-sm">
                      {formatDateTime(report.generatedAt)}
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1 text-xs font-mono text-slate-500">
                        <Hash className="w-3 h-3" />
                        {report.hash}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1 text-xs font-mono text-slate-500">
                        <Package className="w-3 h-3" />
                        {report.evidenceBundleId}
                      </div>
                    </TableCell>
                    <TableCell>
                      <Button 
                        variant="ghost" 
                        size="sm"
                        onClick={() => handleDownloadReport(report)}
                        disabled={!has('REPORT_DOWNLOAD') || downloadingReport === report.reportId}
                      >
                        {downloadingReport === report.reportId ? (
                          <Clock className="w-4 h-4 animate-spin" />
                        ) : (
                          <Download className="w-4 h-4" />
                        )}
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* Evidence Bundles */}
        <Card>
          <CardHeader>
            <CardTitle>Evidence Bundles</CardTitle>
            <CardDescription>
              Supporting documentation and audit evidence. All downloads are logged.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {evidenceBundles.map((bundle) => (
                <div key={bundle.bundleId} className="border rounded-lg p-4">
                  <div className="flex items-center justify-between mb-3">
                    <div>
                      <div className="font-medium">{bundle.bundleId}</div>
                      <div className="text-xs text-slate-500">
                        Created: {formatDateTime(bundle.createdAt)} | Size: {formatBytes(bundle.totalSizeBytes)}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="text-xs font-mono text-slate-500 flex items-center gap-1">
                        <Hash className="w-3 h-3" />
                        {bundle.hash}
                      </div>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => handleDownloadBundle(bundle)}
                        disabled={!has('REPORT_DOWNLOAD') || downloadingBundle === bundle.bundleId}
                      >
                        {downloadingBundle === bundle.bundleId ? (
                          <Clock className="w-4 h-4 mr-1 animate-spin" />
                        ) : (
                          <Download className="w-4 h-4 mr-1" />
                        )}
                        Export
                      </Button>
                    </div>
                  </div>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Document ID</TableHead>
                        <TableHead>Type</TableHead>
                        <TableHead>Hash</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {bundle.documents.map((doc) => (
                        <TableRow key={doc.documentId}>
                          <TableCell className="font-mono text-sm">{doc.documentId}</TableCell>
                          <TableCell>
                            <Badge variant="outline">{doc.documentType.replace(/_/g, ' ')}</Badge>
                          </TableCell>
                          <TableCell className="font-mono text-xs text-slate-500">{doc.hash}</TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Footer */}
        <div className="mt-6 p-4 bg-slate-100 rounded-lg">
          <div className="flex items-center justify-between text-xs text-slate-600">
            <div className="flex items-center gap-2">
              <Hash className="w-4 h-4" />
              <span>All reports are cryptographically hashed. Downloads are logged to the activity timeline.</span>
            </div>
            <div className="font-mono">
              Index retrieved at {new Date().toISOString()}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
